<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AtomPix.Desktop\AtomPix.Desktop.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\TestAssets\Images\png-alpha.png" Link="TestAssets\png-alpha.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
